[tools]
env_create_tool="python3 -m venv"
env_activate_tool="source bin/activate"
env_deactivate_tool="deactivate"
env_name="env"
env_lib_installer="python3 -m pip"

[project]
name="pyappm_server"
version="1.0.0alpha5"
readme="README.md"
license="LICENSE.txt"
description=""
authors=[]
requires_python=">=3.10"
type="application"
dependencies=[
    {name="fastapi", 
    new_packages=["annotated-types", "anyio", "certifi", "click", "dnspython", "email_validator", "exceptiongroup", "fastapi-cli", "h11", "httpcore", "httptools", "httpx", "idna", "itsdangerous", "Jinja2", "markdown-it-py", "MarkupSafe", "mdurl", "orjson", "pydantic", "pydantic-extra-types", "pydantic-settings", "pydantic_core", "Pygments", "python-dotenv", "python-multipart", "PyYAML", "rich", "shellingham", "sniffio", "starlette", "typer", "typing_extensions", "ujson", "uvicorn", "uvloop", "watchfiles", "websockets"]}, 
    {name="pyotp", new_packages=[]}, 
    {name="qrcode", new_packages=["pypng"]}, 
    {name="python-jose", new_packages=["cffi", "cryptography", "ecdsa", "pyasn1", "pycparser", "rsa", "six"]}, 
    {name="passlib", new_packages=[]}, 
    {name="bcrypt", new_packages=[]}, 
    {name="requests", new_packages=["charset-normalizer", "urllib3"]}]

[executable]
app_type="service"
module="pyappm_server"
function="main"

